### ISSUE TITLE
TypeScript error in SinglePickerPanelProps interface during build process

### ISSUE THREAD

**Issue by chaiwei** [react-component/picker#764]
### Reproduction link
[![Edit SinglePickerPanelProps](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/singlepickerpanelprops-ncfsvt?embed=1&file=%2Fsrc%2FApp.tsx)

### Steps to Reproduce:

- Open the reproduction link in CodeSandbox
- Navigate to the build terminal
- Trigger the build process 
- Observe the TypeScript error encountered during the build process.

### What is Expected?
The build process should complete successfully without encountering any TypeScript errors.

### What is Actually Happening?
During the build process, the TypeScript error TS2430 occurs in the file node_modules/rc-picker/lib/PickerPanel/index.d.ts. 

```sh
node_modules/rc-picker/lib/PickerPanel/index.d.ts:40:18 - error TS2430: Interface 'SinglePickerPanelProps<DateType>' incorrectly extends interface 'BasePickerPanelProps<DateType>'.
  Types of property 'defaultValue' are incompatible.
    Type 'DateType | null | undefined' is not assignable to type 'DateType | undefined'.
      Type 'null' is not assignable to type 'DateType | undefined'.

40 export interface SinglePickerPanelProps<DateType extends object = any> extends BasePickerPanelProps<DateType> {
                    ~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/rc-picker/lib/PickerPanel/index.d.ts:40
```

### Additional Comments:

| Dependency  | Version   |
|-------------|-----------|
| antd        | 5.14.1    |
| dayjs       | 1.11.10   |
| react       | ^18.2.0   |
| react-dom   | ^18.2.0   |

**Comment by RickieWoo** [comment]
any solution?

**Comment by chaiwei** [comment]
You can ignore the error by adding "[skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck)": true to your compilerOptions in your `tsconfig.json` file. 

```json
"compilerOptions": {
    // ... the remaining options
    "skipLibCheck": true,
}
```

This will skip type checking of declaration files, which might resolve the TypeScript error you're encountering.

**Comment by authc0d3** [comment]
Any progress with this?

**Comment by ejsinfuego** [comment]
I also come across this issue

@chaiwei already submit a pull request. Thank you.

**Comment by afc163** [comment]
Fixed in latest version already: https://codesandbox.io/p/devbox/singlepickerpanelprops-forked-txzhjt?file=%2Fsrc%2FApp.tsx%3A18%2C18&workspaceId=fb8d496a-cbdc-482b-9003-b38c3155f290

**Comment by mperdikeas** [comment]
I believe this fix / pull request is still not accepted / merged (as of release 4.8.3)

**Comment by SimoneLucato0** [comment]
I still have this issue from building with `antd@5.23.1` using `rc-picker@4.9.2` (current latest versions of both libraries)

**Comment by gnanarabin** [comment]
"antd": "^6.6.2",
 "react": "^19.3.0",
 "react-dom": "^19.3.0",

 "devDependencies": {
    "typescript": "~6.0.2",
}

using vite , 

1. node_modules/@rc-component/image/es/PreviewGroup.d.ts:6:18 - error TS2430: Interface 'GroupPreviewConfig' incorrectly extends interface 'InternalPreviewConfig'.
  Types of property 'imageRender' are incompatible.
    Type '((originalNode: ReactElement<unknown, string | JSXElementConstructor<any>>, info: { transform: TransformType; current: number; image: ImgInfo; }) => ReactNode) | undefined' is not assignable to type '((originalNode: ReactElement<unknown, string | JSXElementConstructor<any>>, info: {transform: TransformType; current?: number | undefined; image: ImgInfo; }) => ReactNode) | undefined'.
      Type '(originalNode: ReactElement<unknown, string | JSXElementConstructor<any>>, info: { transform: TransformType; current: number; image: ImgInfo; }) => ReactNode' is not assignable to type '(originalNode: ReactElement<unknown, string | JSXElementConstructor<any>>, info: { transform: TransformType; current?: number | undefined; image: ImgInfo; }) => ReactNode'.
        Types of parameters 'info' and 'info' are incompatible.
          Type '{ transform: TransformType; current?: number | undefined; image: ImgInfo; }' is not assignable to type '{ transform: TransformType; current: number; image: ImgInfo; }'.
            Types of property 'current' are incompatible.
              Type 'number | undefined' is not assignable to type 'number'.
                Type 'undefined' is not assignable to type 'number'.

6 export interface GroupPreviewConfig extends InternalPreviewConfig {
                   ~~~~~~~~~~~~~~~~~~
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2. node_modules/@rc-component/picker/es/PickerPanel/index.d.ts:40:18 - error TS2430: Interface 'SinglePickerPanelProps<DateType>' incorrectly extendsinterface 'BasePickerPanelProps<DateType>'.
  Types of property 'defaultValue' are incompatible.
    Type 'DateType | null | undefined' is not assignable to type 'DateType | undefined'.
      Type 'null' is not assignable to type 'DateType | undefined'.

40 export interface SinglePickerPanelProps<DateType extends object = any> extends BasePickerPanelProps<DateType> {
       


gettings tose 2 errors ,

should not use skipLibCheck=true
